name: product_store
on:
  schedule:
  - cron: "0 2 * * 6"
  workflow_dispatch:
    inputs:
      test_browser:
        description: 'browser'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox

env:
  APP_BRANCH: "${{github.ref_name}}"
  BROWSER: "${{github.event.inputs.test_browser}}"
  
jobs:
  product_store:
    name: Test on node ${{ matrix.node_version }} with ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        node_version: ['18']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{env.APP_BRANCH}}
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Install playwright dependencies
        run: npx playwright install --with-deps "${{env.BROWSER}}"
        
      - name: Run tests
        run: yarn test-"${{env.BROWSER}}"
        
      - name: Upload allure results artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifact-results
          path: allure-results
          if-no-files-found: error
          retention-days: 1

  deploy_report:
    runs-on: ubuntu-latest
    needs: [product_store]
    permissions:
      contents: write
    steps:
      - name: Get History
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Get results artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact-results
          path: allure-results

      - name: Generate report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: ./
          keep-reports: 1000

      - name: Deploy report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true

  notify:
    name: Notify to telegram
    runs-on: ubuntu-latest
    needs: [deploy_report]
    steps:
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}  
          message: |
            The new report was generated:
            https://ar7nic.github.io/product_store/${{github.run_number}}/
        
