name: product_store
on:
  schedule:
  - cron: "0 2 * * 6"
  workflow_dispatch:

env:
  APP_BRANCH: main
  
jobs:
  product_store:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        node_version: ['18']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{env.APP_BRANCH}}
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Install playwright dependencies
        run: npx playwright install --with-deps chromium
        
      - name: Run tests
        run: yarn test:reporter
        
      - name: Upload allure results artifacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: artifact-results
          path: allure-results
          if-no-files-found: error
          retention-days: 1
          
        
        
          
        
